/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JFrame;

/**
 *
 * @author hp
 */
public class NewJFrame3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame3.class.getName());

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
         initComponents();
         setResizable(true);
         setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSpinner1 = new javax.swing.JSpinner();
        espaceRechercher = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nomFenètre = new javax.swing.JLabel();
        btnajouterPassager = new javax.swing.JButton();
        listePassagerSroll = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        quitterOnglet = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        btnModifierPassager = new javax.swing.JButton();
        btnDeletePassager = new javax.swing.JButton();
        GébereTicket = new javax.swing.JButton();
        btnRechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTE DES PASSAGERS");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nomFenètre.setBackground(new java.awt.Color(255, 51, 255));
        nomFenètre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nomFenètre.setForeground(new java.awt.Color(102, 102, 255));
        nomFenètre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomFenètre.setText("LISTE DES PASSAGERS");

        btnajouterPassager.setBackground(new java.awt.Color(255, 51, 204));
        btnajouterPassager.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnajouterPassager.setText("AJOUTER PASSAGER");
        btnajouterPassager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterPassagerActionPerformed(evt);
            }
        });

        listePassagerSroll.setBorder(null);

        jTable1.setForeground(new java.awt.Color(153, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prénoms", "E-mail", "Téléphone", "Voyage"
            }
        ));
        listePassagerSroll.setViewportView(jTable1);

        quitterOnglet.setBackground(new java.awt.Color(0, 0, 255));
        quitterOnglet.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        quitterOnglet.setText("Fermer ");
        quitterOnglet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterOngletActionPerformed(evt);
            }
        });

        btnModifierPassager.setBackground(new java.awt.Color(204, 0, 255));
        btnModifierPassager.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnModifierPassager.setText("Modifier Passager");
        btnModifierPassager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierPassagerActionPerformed(evt);
            }
        });

        btnDeletePassager.setBackground(new java.awt.Color(0, 153, 0));
        btnDeletePassager.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDeletePassager.setText("Supprimer Passager");
        btnDeletePassager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePassagerActionPerformed(evt);
            }
        });

        GébereTicket.setBackground(new java.awt.Color(0, 153, 153));
        GébereTicket.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        GébereTicket.setText("Génerer ticket");
        GébereTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GébereTicketActionPerformed(evt);
            }
        });

        btnRechercher.setBackground(new java.awt.Color(102, 102, 255));
        btnRechercher.setText("Rechercher");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(nomFenètre, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnajouterPassager, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnModifierPassager, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnDeletePassager)
                .addGap(52, 52, 52)
                .addComponent(GébereTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(quitterOnglet, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listePassagerSroll)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(nomFenètre)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnajouterPassager, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(listePassagerSroll, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifierPassager, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePassager, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitterOnglet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GébereTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnajouterPassagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterPassagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnajouterPassagerActionPerformed

    private void quitterOngletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterOngletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitterOngletActionPerformed

    private void btnModifierPassagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierPassagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierPassagerActionPerformed

    private void btnDeletePassagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePassagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletePassagerActionPerformed

    private void GébereTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GébereTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GébereTicketActionPerformed

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRechercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GébereTicket;
    private javax.swing.JButton btnDeletePassager;
    private javax.swing.JButton btnModifierPassager;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton btnajouterPassager;
    private javax.swing.JLabel espaceRechercher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JScrollPane listePassagerSroll;
    private javax.swing.JLabel nomFenètre;
    private javax.swing.JButton quitterOnglet;
    // End of variables declaration//GEN-END:variables
}
