/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package mvc_voyage.view;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.util.Date;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author macbook
 */
public class FicheVoyageView extends javax.swing.JFrame {

    /**
     * Creates new form FicheVoyageView
     */
    public FicheVoyageView() {
        initComponents();
        setLocationRelativeTo(null);
        // Ajuster la taille de la fenêtre
        setSize(750, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfLieuDepart = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfLieuArrive = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btEnregistrer = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfPrix = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfSiegesReserves = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfBateauId = new javax.swing.JTextField();
        btCalculerDuree = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tfDuree = new javax.swing.JTextField();
        
        // Panels pour date et heure
        panelDateDepart = new javax.swing.JPanel();
        dateDepart = new com.toedter.calendar.JDateChooser();
        spinnerHeureDepart = new javax.swing.JSpinner();
        
        panelDateArrive = new javax.swing.JPanel();
        dateArrive = new com.toedter.calendar.JDateChooser();
        spinnerHeureArrive = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 800)); // Taille de la fenêtre

        jPanel1.setPreferredSize(new java.awt.Dimension(730, 1100)); // Hauteur augmentée

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copyright (c) KOUASSI 2025");

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fiche Voyage");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tfLieuDepart.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // Taille réduite
        tfLieuDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLieuDepartActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 204, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Lieu d'arrivée");

        tfLieuArrive.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // Taille réduite
        tfLieuArrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLieuArriveActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 204, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Date et heure d'arrivée");

        jLabel5.setBackground(new java.awt.Color(0, 204, 255));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Date et heure de départ");

        btEnregistrer.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        btEnregistrer.setText("✅ Enregistrer");
        btEnregistrer.setBackground(new java.awt.Color(0, 153, 0));
        btEnregistrer.setForeground(java.awt.Color.WHITE);
        btEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnregistrerActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(0, 204, 255));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("*");

        jLabel7.setBackground(new java.awt.Color(0, 204, 255));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Lieu de départ");

        jLabel8.setBackground(new java.awt.Color(0, 204, 255));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("*");

        jLabel9.setBackground(new java.awt.Color(0, 204, 255));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("*");

        jLabel10.setBackground(new java.awt.Color(0, 204, 255));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Prix");

        tfPrix.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // Taille réduite

        jLabel11.setBackground(new java.awt.Color(0, 204, 255));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Sièges réservés");

        tfSiegesReserves.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // Taille réduite

        jLabel12.setBackground(new java.awt.Color(0, 204, 255));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("ID Bateau");

        tfBateauId.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // Taille réduite

        btCalculerDuree.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btCalculerDuree.setText("Calculer Durée");
        btCalculerDuree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculerDureeActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 204, 255));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // Taille réduite
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Durée (HH:MM)");

        tfDuree.setEditable(false);
        tfDuree.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // Taille réduite

        // Configuration du panel pour date et heure de départ
        panelDateDepart.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        dateDepart.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        dateDepart.setPreferredSize(new java.awt.Dimension(200, 25));
        
        spinnerHeureDepart.setModel(new javax.swing.SpinnerDateModel());
        spinnerHeureDepart.setEditor(new javax.swing.JSpinner.DateEditor(spinnerHeureDepart, "HH:mm"));
        spinnerHeureDepart.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        spinnerHeureDepart.setPreferredSize(new java.awt.Dimension(80, 25));
        
        panelDateDepart.add(dateDepart);
        panelDateDepart.add(spinnerHeureDepart);

        // Configuration du panel pour date et heure d'arrivée
        panelDateArrive.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        dateArrive.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        dateArrive.setPreferredSize(new java.awt.Dimension(200, 25));
        
        spinnerHeureArrive.setModel(new javax.swing.SpinnerDateModel());
        spinnerHeureArrive.setEditor(new javax.swing.JSpinner.DateEditor(spinnerHeureArrive, "HH:mm"));
        spinnerHeureArrive.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        spinnerHeureArrive.setPreferredSize(new java.awt.Dimension(80, 25));
        
        panelDateArrive.add(dateArrive);
        panelDateArrive.add(spinnerHeureArrive);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfLieuDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfLieuArrive, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(panelDateDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(panelDateArrive, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfSiegesReserves, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfBateauId, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCalculerDuree))
                    .addComponent(tfDuree, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(527, Short.MAX_VALUE)))
        );
        
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80) // Espace réduit en haut
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLieuDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLieuArrive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDateDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDateArrive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSiegesReserves, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBateauId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalculerDuree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDuree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1030, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(450, 450, 450)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(625, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void tfLieuDepartActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void tfLieuArriveActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btCalculerDureeActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    // Méthodes pour obtenir les dates complètes avec heure
    public Date getDateHeureDepart() {
        Date date = dateDepart.getDate();
        Date time = (Date) spinnerHeureDepart.getValue();
        
        if (date != null && time != null) {
            java.util.Calendar calDate = java.util.Calendar.getInstance();
            calDate.setTime(date);
            
            java.util.Calendar calTime = java.util.Calendar.getInstance();
            calTime.setTime(time);
            
            calDate.set(java.util.Calendar.HOUR_OF_DAY, calTime.get(java.util.Calendar.HOUR_OF_DAY));
            calDate.set(java.util.Calendar.MINUTE, calTime.get(java.util.Calendar.MINUTE));
            calDate.set(java.util.Calendar.SECOND, 0);
            calDate.set(java.util.Calendar.MILLISECOND, 0);
            
            return calDate.getTime();
        }
        return date;
    }
    
    public Date getDateHeureArrive() {
        Date date = dateArrive.getDate();
        Date time = (Date) spinnerHeureArrive.getValue();
        
        if (date != null && time != null) {
            java.util.Calendar calDate = java.util.Calendar.getInstance();
            calDate.setTime(date);
            
            java.util.Calendar calTime = java.util.Calendar.getInstance();
            calTime.setTime(time);
            
            calDate.set(java.util.Calendar.HOUR_OF_DAY, calTime.get(java.util.Calendar.HOUR_OF_DAY));
            calDate.set(java.util.Calendar.MINUTE, calTime.get(java.util.Calendar.MINUTE));
            calDate.set(java.util.Calendar.SECOND, 0);
            calDate.set(java.util.Calendar.MILLISECOND, 0);
            
            return calDate.getTime();
        }
        return date;
    }
    
    // Méthodes pour définir les dates complètes avec heure
    public void setDateHeureDepart(Date dateTime) {
        if (dateTime != null) {
            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.setTime(dateTime);
            
            java.util.Calendar dateOnly = java.util.Calendar.getInstance();
            dateOnly.set(cal.get(java.util.Calendar.YEAR), 
                        cal.get(java.util.Calendar.MONTH), 
                        cal.get(java.util.Calendar.DAY_OF_MONTH));
            dateDepart.setDate(dateOnly.getTime());
            
            java.util.Calendar timeOnly = java.util.Calendar.getInstance();
            timeOnly.set(0, 0, 0, 
                        cal.get(java.util.Calendar.HOUR_OF_DAY), 
                        cal.get(java.util.Calendar.MINUTE));
            spinnerHeureDepart.setValue(timeOnly.getTime());
        }
    }
    
    public void setDateHeureArrive(Date dateTime) {
        if (dateTime != null) {
            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.setTime(dateTime);
            
            java.util.Calendar dateOnly = java.util.Calendar.getInstance();
            dateOnly.set(cal.get(java.util.Calendar.YEAR), 
                        cal.get(java.util.Calendar.MONTH), 
                        cal.get(java.util.Calendar.DAY_OF_MONTH));
            dateArrive.setDate(dateOnly.getTime());
            
            java.util.Calendar timeOnly = java.util.Calendar.getInstance();
            timeOnly.set(0, 0, 0, 
                        cal.get(java.util.Calendar.HOUR_OF_DAY), 
                        cal.get(java.util.Calendar.MINUTE));
            spinnerHeureArrive.setValue(timeOnly.getTime());
        }
    }

    public JButton getBtCalculerDuree() {
        return btCalculerDuree;
    }

    public JButton getBtEnregistrer() {
        return btEnregistrer;
    }

    public JDateChooser getDateArrive() {
        return dateArrive;
    }
    
    public JDateChooser getDateDepart() {
        return dateDepart;
    }
    
    public JSpinner getSpinnerHeureDepart() {
        return spinnerHeureDepart;
    }
    
    public JSpinner getSpinnerHeureArrive() {
        return spinnerHeureArrive;
    }

    public JTextField getTfBateauId() {
        return tfBateauId;
    }

    public JTextField getTfDuree() {
        return tfDuree;
    }

    public JTextField getTfLieuArrive() {
        return tfLieuArrive;
    }

    public JTextField getTfLieuDepart() {
        return tfLieuDepart;
    }

    public JTextField getTfPrix() {
        return tfPrix;
    }

    public JTextField getTfSiegesReserves() {
        return tfSiegesReserves;
    }
    
    public JScrollPane getScrollPane() {
        return jScrollPane1;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btCalculerDuree;
    private javax.swing.JButton btEnregistrer;
    private com.toedter.calendar.JDateChooser dateArrive;
    private com.toedter.calendar.JDateChooser dateDepart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDateArrive;
    private javax.swing.JPanel panelDateDepart;
    private javax.swing.JSpinner spinnerHeureArrive;
    private javax.swing.JSpinner spinnerHeureDepart;
    private javax.swing.JTextField tfBateauId;
    private javax.swing.JTextField tfDuree;
    private javax.swing.JTextField tfLieuArrive;
    private javax.swing.JTextField tfLieuDepart;
    private javax.swing.JTextField tfPrix;
    private javax.swing.JTextField tfSiegesReserves;
    // End of variables declaration                   
}